trigger:
  branches:
    include:
      - main
    exclude:
      - release-candidate

  paths:
    include:
      - src
    exclude:
      - script/*
      - libs/*
      - devops/*

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
        - main

resources:
  repositories:
    # For type: github, name is <identity>/<repo> as in the examples above. For type: git (Azure Repos), name is <project>/<repo>.
    - repository: coreTemplates
      type: git
      name: Umbrella/Umbrella.Devops
      ref: refs/heads/main
      endpoint: Garaproject

parameters:
  - name: inputSonarScanEnabled
    displayName: "Enable Sonar Scan"
    type: boolean
    default: True
  - name: inputPublishPackage
    displayName: "Publish Package to Nuget.Org"
    type: boolean
    default: False

extends:
  template: dotnet-pakages-pipeline.1.2.yaml@coreTemplates
  parameters:
    MajorVersion: 2
    MinorVersion: 0
    PatchVersion: 1
    SonarScanEnabled: ${{ parameters.inputSonarScanEnabled }}
    SonarSettings:
      ProjectKey: Umbrella.Infrastructure
      ProjectName: Umbrella.Infrastructure
      TestReportFileName: cobertura.xml
    PublishPackage: ${{ parameters.inputPublishPackage }}
    NugetSecretFileName: Nuget.apikey.txt
    ListOfProjToBuild:
      - path: src/Umbrella.Infrastructure.Tests
        name: Umbrella.Infrastructure.Tests
        publishRequired: false
        isWebProj: False
      - path: src/Umbrella.Logging
        name: Umbrella.Logging
        publishRequired: false
        isWebProj: False
      - path: src/Umbrella.Infrastructure.Cache.Tests
        name: Umbrella.Infrastructure.Cache.Tests
        publishRequired: false
        isWebProj: False
      - path: src/Umbrella.Infrastructure.Firestore.Tests
        name: Umbrella.Infrastructure.Firestore.Tests
        publishRequired: false
        isWebProj: False
      - path: src/Umbrella.Infrastructure.FileStorage.Tests
        name: Umbrella.Infrastructure.FileStorage.Tests
        publishRequired: false
        isWebProj: False
      - path: src/Umbrella.Infrastructure.Templating.Tests
        name: Umbrella.Infrastructure.Templating.Tests
        publishRequired: false
        isWebProj: False
      - path: src/Umbrella.Security.Tests
        name: Umbrella.Security.Tests
        publishRequired: false
        isWebProj: False
    ListOfProjToTest:
      - path: src/Umbrella.Infrastructure.Tests
        name: Umbrella.Infrastructure.Tests
        #Cache
      - path: src/Umbrella.Infrastructure.Cache.Tests
        name: Umbrella.Infrastructure.Cache.Tests
        # FileStorage
      - path: src/Umbrella.Infrastructure.FileStorage.Tests
        name: Umbrella.Infrastructure.FileStorage.Tests
        # Firestore
      # - path: src/Umbrella.Infrastructure.Firestore.Tests
      #   name: Umbrella.Infrastructure.Firestore.Tests
      # Templating
      - path: src/Umbrella.Infrastructure.Templating.Tests
        name: Umbrella.Infrastructure.Templating.Tests
        # Security
      - path: src/Umbrella.Security.Tests
        name: Umbrella.Security.Tests
    ListOfProjToPublish:
      - path: src/Umbrella.Infrastructure
        name: Umbrella.Infrastructure
        # Cache
      - path: src/Umbrella.Infrastructure.Cache
        name: Umbrella.Infrastructure.Cache
        # Filestore
      - path: src/Umbrella.Infrastructure.FileStorage
        name: Umbrella.Infrastructure.FileStorage
        # Flistorage GCP
      - path: src/Umbrella.Infrastructure.FileStorage.GoogleCloudStorage
        name: Umbrella.Infrastructure.FileStorage.GoogleCloudStorage
        # Firestore
      - path: src/Umbrella.Infrastructure.Firestore
        name: Umbrella.Infrastructure.Firestore
        # Templating
      - path: src/Umbrella.Infrastructure.Templating
        name: Umbrella.Infrastructure.Templating
        # Logging
      - path: src/Umbrella.Logging
        name: Umbrella.Logging
        # Security
      - path: src/Umbrella.Security
        name: Umbrella.Security
