trigger:
  branches:
    include:
      - main
    exclude:
      - master
      - develop
      - release-candidate

  paths:
    include:
      - src
    exclude:
      - script/*
      - libs/*
      - devops/*

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
        - main

resources:
  repositories:
    # For type: github, name is <identity>/<repo> as in the examples above. For type: git (Azure Repos), name is <project>/<repo>.
    - repository: coreTemplates
      type: git
      name: Umbrella/Umbrella.Devops
      ref: refs/heads/main
      endpoint: Garaproject

parameters:
  - name: inputSonarScanEnabled
    displayName: "Enable Sonar Scan"
    type: boolean
    default: False
  - name: inputPublishPackage
    displayName: "Publish Package to Nuget.Org"
    type: boolean
    default: False

extends:
  template: dotnet-pakages-pipeline.1.2.yaml@coreTemplates
  parameters:
    MajorVersion: 1
    MinorVersion: 0
    PatchVersion: 0
    SonarScanEnabled: False
    PublishPackage: False
    NugetSecretFileName: Nuget.apikey.txt
    ListOfProjToBuild:
      - path: src/Umbrella.Infrastructure.Tests
        name: Umbrella.Infrastructure.Tests
        publishRequired: false
        isWebProj: False
    ListOfProjToPublish:
      - path: src/Umbrella.Infrastructure
        name: Umbrella.Infrastructure
        publishRequired: false
        isWebProj: False
    ListOfProjToTest:
      - path: src/Umbrella.Infrastructure.Tests
        name: Umbrella.Infrastructure.Tests
